# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: ununennium
open_collective: ununennium
ko_fi: ununennium
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: ununennium
issuehunt: ununennium
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: ununennium
buy_me_a_coffee: ununennium
thanks_dev: ununennium
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
