{% set name = "ununennium" %}
{% set version = "1.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.10
    - hatchling
    - pip
  run:
    - python >=3.10
    - numpy >=1.24.0
    - pytorch >=2.4.0
    - einops >=0.7.0
    - typing-extensions >=4.0.0
    - affine >=2.4.0

test:
  imports:
    - ununennium
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/olaflaitinen/ununennium
  summary: Production-grade Python library for satellite and geospatial imagery machine learning
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/olaflaitinen/ununennium
  doc_url: https://olaflaitinen.github.io/ununennium

extra:
  recipe-maintainers:
    - olaflaitinen
